bugfix/empty client id and not sent connack
hivemq/hivemq-community-edition pull request #203
Opened 2020-08-24 11:17 UTC by Florian-Limpoeck

**Motivation**

configuration for allowEmptyClientIdentifier is unused for mqtt 3 clients.
connacks where no client id is set to channel attributes are not sent.

**Changes**

config now used for mqtt 3 clients.
connacks are now sent correctly.

2020-08-24 14:51 UTC, schaebo approved these changes

2020-08-24 14:53 UTC, schaebo requested changes

2020-08-24 14:53 UTC, schaebo commented on src/test/java/com/hivemq/codec/decoder/Mqtt31ConnectDecoderTest.java
> +                new ClientIds(new ClusterId()), new TestConfigurationBootstrap().getFullConfigurationService(),
This does not compile, i think this has a different constructor with HivemqId

2020-08-24 16:15 UTC, LBrandl commented on src/test/java/com/hivemq/codec/decoder/Mqtt31ConnectDecoderValidationsTest.java
> +                new ClientIds(new ClusterId()), new TestConfigurationBootstrap().getFullConfigurationService(),
ClusterId -> HivemqId

2020-08-24 16:15 UTC, LBrandl commented on src/test/java/com/hivemq/codec/decoder/mqtt311/Mqtt311ConnectDecoderInvalidFixedHeadersTest.java
> +                new ClientIds(new ClusterId()), new TestConfigurationBootstrap().getFullConfigurationService(),
ClusterId -> HivemqId

2020-08-24 16:15 UTC, LBrandl commented on src/test/java/com/hivemq/codec/decoder/mqtt311/Mqtt311ConnectDecoderTest.java
> +    private ClusterId clusterId;
ClusterId -> HivemqId

2020-08-24 16:15 UTC, LBrandl commented on src/test/java/com/hivemq/codec/decoder/mqtt311/Mqtt311ConnectDecoderValidationsTest.java
> +                new ClientIds(new ClusterId()), new TestConfigurationBootstrap().getFullConfigurationService(),
ClusterId -> HivemqId

2020-08-24 16:16 UTC, LBrandl commented on src/test/java/com/hivemq/codec/decoder/mqtt311/Mqtt311ConnectDecoderValidationsTest.java
> +                new ClusterId());
ClusterId -> HivemqId

2020-08-24 16:25 UTC, LBrandl approved these changes

2020-08-25 17:53 UTC, schaebo approved these changes

2020-08-25 17:54 UTC, merged