fix keepalive idle handler parameterization
hivemq/hivemq-community-edition pull request #204
Opened 2020-08-25 10:38 UTC by sbaier1

**Motivation**

Resolves ID:394

**Changes**

fix keepalive idle handler parameterization

2020-08-25 10:53 UTC, Florian-Limpoeck commented on src/test/java/com/hivemq/mqtt/handler/connect/ConnectHandlerTest.java
> +        boolean containsHandler = false;
please add more unit tests, as you just added three more conditions

2020-08-25 10:53 UTC, Florian-Limpoeck requested changes
please add more unit tests

2020-08-25 12:58 UTC, LBrandl approved these changes

2020-08-26 08:34 UTC, Florian-Limpoeck approved these changes

2020-09-01 15:21 UTC, merged