Build improvements
hivemq/hivemq-community-edition pull request #267
Opened 2021-04-20 14:32 UTC by SgtSilvio

**Motivation**

**Changes**

2021-04-21 13:44 UTC, gitseti commented on build.gradle.kts
> +val hivemqZip by tasks.registering(Zip::class) {
Are you sure about renaming the task `packaging` to `hivemqZip`

2021-04-21 13:50 UTC, gitseti approved these changes

2021-05-11 11:51 UTC, A-Imal requested changes

2021-05-11 11:51 UTC, A-Imal commented on README.adoc
> +./gradlew
```suggestion
./gradlew hivemqZip
```

2021-05-11 11:51 UTC, A-Imal commented on docker/build.sh
> +./gradlew
```suggestion
./gradlew hivemqZip
```

2021-05-11 14:25 UTC, merged